# Generated by Django 6.0.4 on 2026-04-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISupportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Основні налаштування', max_length=100, verbose_name='Назва')),
                ('system_prompt', models.TextField(verbose_name='Системний промпт')),
                ('model_name', models.CharField(choices=[('gemini-2.5-flash', 'Gemini 2.5 Flash'), ('gemini-2.5-flash-lite', 'Gemini 2.5 Flash-Lite'), ('gemini-2.5-pro', 'Gemini 2.5 Pro'), ('gemini-2.0-flash', 'Gemini 2.0 Flash')], default='gemini-2.0-flash', max_length=100, verbose_name='Модель')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Налаштування чату ШІ Підтримки',
                'verbose_name_plural': 'Налаштування чату ШІ Підтримки',
            },
        ),
    ]
