# Generated by Django 6.0.4 on 2026-04-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aisupport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisupportsettings',
            name='model_name',
            field=models.CharField(choices=[('gemma-3-4b-it', 'Gemma 3 4B'), ('gemma-3-12b-it', 'Gemma 3 12B'), ('gemma-3-27b-it', 'Gemma 3 27B'), ('gemini-2.5-flash', 'Gemini 2.5 Flash'), ('gemini-2.5-flash-lite', 'Gemini 2.5 Flash-Lite'), ('gemini-2.5-pro', 'Gemini 2.5 Pro'), ('gemini-2.0-flash', 'Gemini 2.0 Flash')], default='gemma-3-27b-it', max_length=100, verbose_name='Модель'),
        ),
    ]
