# Generated by Django 6.0.4 on 2026-05-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aisupport', '0002_alter_aisupportsettings_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisupportsettings',
            name='model_name',
            field=models.CharField(choices=[('gemma-4-31b-it', 'Gemma 4 31B'), ('gemini-2.5-flash', 'Gemini 2.5 Flash'), ('gemini-2.5-flash-lite', 'Gemini 2.5 Flash-Lite'), ('gemini-2.5-pro', 'Gemini 2.5 Pro'), ('gemini-2.0-flash', 'Gemini 2.0 Flash')], default='gemma-4-31b-it', max_length=100, verbose_name='Модель'),
        ),
    ]
