# Generated by Django 6.0.4 on 2026-04-20 15:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Код категорії')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я категорії")),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Категорія волонтерства',
                'verbose_name_plural': 'Категорії волонтерства',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Код волонтерства')),
                ('name', models.CharField(max_length=100)),
                ('main_description', models.TextField(default='Ваш опис', verbose_name='Короткий опис')),
                ('description', models.TextField(verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='volunteers')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='volunteers.category', verbose_name='Категорія волонтерства')),
            ],
            options={
                'verbose_name': 'Волонтерство',
                'verbose_name_plural': 'Волонтерства',
            },
        ),
    ]
