# Generated by Django 6.0.4 on 2026-04-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_advertisement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Реклама', 'verbose_name_plural': 'Реклами'},
        ),
    ]
