# Generated by Django 6.0.4 on 2026-04-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_alter_advertisement_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmoderatedVolunteer',
            fields=[
            ],
            options={
                'verbose_name': 'Волонтерство на модерації',
                'verbose_name_plural': 'Волонтерства на модерації',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('volunteers.volunteer',),
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія волонтерства', 'verbose_name_plural': 'Категорії волонтерств'},
        ),
        migrations.AddField(
            model_name='volunteer',
            name='moderated',
            field=models.BooleanField(default=False, verbose_name='Модерація пройдена'),
        ),
    ]
