# Generated by Django 6.0.4 on 2026-04-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0005_unmoderatedvolunteer_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='highlight_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Виділено до'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='is_highlighted',
            field=models.BooleanField(default=False, verbose_name='Прорекламовано'),
        ),
    ]
