# Generated by Django 6.0.4 on 2026-04-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='moderated',
            field=models.BooleanField(default=False, verbose_name='Модерація пройдена'),
        ),
    ]
