# Generated by Django 6.0.4 on 2026-04-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_moderated'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmoderatedArticle',
            fields=[
            ],
            options={
                'verbose_name': 'Стаття на модерації',
                'verbose_name_plural': 'Статті на модерації',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('articles.article',),
        ),
    ]
