# Generated by Django 6.0.4 on 2026-04-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_unmoderatedarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
